### ISSUE TITLE
Windows IoT Core

### ISSUE THREAD

**Issue by allbabel** [webrtc-uwp/webrtc-uwp-sdk#9] opened 2017-07-25 09:54 UTC
Hi,

I just tried to run the PeerCCSample application using the latest NuGet package and it crashes within WebRTC when initialising on a RPi3 running Windows IoT Core.  Is this supposed to run or even supported on Windows IoT Core?

Thanks, Andy

**Comment by NVgithub** [comment] 2017-07-27 08:31
Hello,

I have the same problem when calling Org.WebRtc.WebRTC.Initialize(null). The method throws an exception but if the Windows is not with Creators Update the exception does not crash the app. However if I run the app on Windows with Creators Update the exception crashes the app altogether.

**Comment by jamescadd** [comment] 2018-04-16 17:41
Duplicate of #20

**Closed by jamescadd** 2018-04-16 17:41 UTC
