### ISSUE TITLE
Ability to create a custom video stream?

### ISSUE THREAD

**Issue by galli-leo** [webrtc-uwp/webrtc-uwp-sdk#12] opened 2017-10-04 08:29 UTC
Hi,

I would like to use this library on the Hololens and send a mixed reallity capture to the receiver. For this I would need the ability to send custom frames to a custom video stream, just like the iOS framework allows. Is this something that's possible / planned?

If not, could you point me in the right direction, where I might add such functionality?

**Comment by jamescadd** [comment] 2017-10-06 20:03
Hello, we are currently working on a Unity sample to do this.  While I don't have an exact ETA I'd hope to have this ready by end of month, potentially with something for you to preview sooner.  I'd be interested to hear more about your scenario and what other features may be useful - feel free to reach out at jacadd@microsoft.com to discuss further.

**Comment by HoloJackStones** [comment] 2017-11-07 15:13
any news about the feature?

**Comment by jamescadd** [comment] 2017-11-07 17:45
@HoloJackStones This is currently under development but not yet complete.  As soon as there's something early to share I'll update the issue, hopefully within 2 weeks or so.

**Comment by HoloJackStones** [comment] 2017-11-07 17:48
@jamescadd thanks. As you can imagine, this feature will be useful for the scenario we talked about some weeks ago (sending data stored in frames for sync data and video).

**Comment by besserwisser** [comment] 2018-05-16 14:36
@jamescadd Are there any news on your project?

**Comment by jamescadd** [comment] 2018-05-16 15:27
@besserwisser Yes, MRC is currently confirmed working in this branch: https://github.com/ortclib/ortclib-sdk/tree/Mosa/20180320-peercc-unity

Then open WebRtcUnityD3D.sln from the solutions folder.  This is new though and not thoroughly tested, once we have updated the NuGet package I'll close the issue.

**Comment by Festyk** [comment] 2018-05-17 06:42
I've got an error trying to build WebRtcUnityD3D.sln. The problem is with Org.WebRtc.Uwp and output says: "LINK : fatal error LNK1104: cannot open file 'webrtc.lib'"

**Comment by jamescadd** [comment] 2018-05-17 15:07
@Festyk You can find the MRC code here: https://github.com/webrtc-uwp/webrtc/blob/e2ba4452b1a1d0667d39144823193908fa943530/webrtc/modules/video_capture/windows/video_capture_winuwp.cc#L417 It's currently enabled by default but we're working on making this available via API.  You can access a single frame (assuming you want decoded bits) for the VP8 codec only currently, but that can be done via the MediaVideoTrack.OnRawVideoFrame event like so:

`MediaVideoTrack videoTrack;
RawVideoSource rawVideoSource;
rawVideoSource = Media.CreateMedia().CreateRawVideoSource(videoTrack);
rawVideoSource.OnRawVideoFrame += (width, height,
    yPlane, yPitch,
    vPlane, vPitch,
    uPlane, uPitch) =>
{
    Debug.WriteLine("Raw video frame received");
};`

Disclaimer: I have not tried the raw frame access via latest source on HoloLens.

**Comment by jamescadd** [comment] 2018-06-26 15:20
The Unity codebase is now available in master for the PeerCC-Sample repo.  It'll be merged to master for webrtc-sdk next week.

**Closed by jamescadd** 2018-06-26 15:20 UTC
