### ISSUE TITLE
Issues building "releases/m62" branch

### ISSUE THREAD

**Issue by joe-imajion** [webrtc-uwp/webrtc-uwp-sdk#69] opened 2018-09-25 10:55 UTC
Hi,

I'm able to recursive clone webrtc-uwp-sdk, checkout "release/m62", sync and update the submodules, and run bin\prepare.bat successfully.

However, if I try to build "WebRtc.UWP.Native.Builder" inside the Visual Studio solution "webrtc-uwp-sdk\webrtc\windows\solutions\WebRtc.sln" with Debug and x86, I get the following errors:

```
2>FAILED: obj/webrtc/rtc_base/rtc_base_approved/platform_file.obj
2>ninja -t msvc -e environment.winuwp_x86 -- "c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\bin\hostx64\x86\cl.exe" /nologo /showIncludes  @obj/webrtc/rtc_base/rtc_base_approved/platform_file.obj.rsp /c ../../webrtc/rtc_base/platform_file.cc /Foobj/webrtc/rtc_base/rtc_base_approved/platform_file.obj /Fd"obj/webrtc/rtc_base/rtc_base_approved_cc.pdb"
2>../../webrtc/rtc_base/platform_file.cc(46): error C2039: 'CreateFile': is not a member of '`global namespace''
2>../../webrtc/rtc_base/platform_file.cc(46): error C3861: 'CreateFile': identifier not found
2>../../webrtc/rtc_base/platform_file.cc(51): error C2039: 'CreateFile': is not a member of '`global namespace''
2>../../webrtc/rtc_base/platform_file.cc(51): error C3861: 'CreateFile': identifier not found
2>[2/1879] CXX obj/webrtc/rtc_base/rtc_base_approved/flags.obj
2>FAILED: obj/webrtc/rtc_base/rtc_base_approved/flags.obj
2>ninja -t msvc -e environment.winuwp_x86 -- "c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\bin\hostx64\x86\cl.exe" /nologo /showIncludes  @obj/webrtc/rtc_base/rtc_base_approved/flags.obj.rsp /c ../../webrtc/rtc_base/flags.cc /Foobj/webrtc/rtc_base/rtc_base_approved/flags.obj /Fd"obj/webrtc/rtc_base/rtc_base_approved_cc.pdb"
2>../../webrtc/rtc_base/flags.cc(273): error C2039: 'CommandLineToArgvW': is not a member of '`global namespace''
2>../../webrtc/rtc_base/flags.cc(273): error C3861: 'CommandLineToArgvW': identifier not found
```

If I try to build Debug and x64 I get a slightly different build error, but they are still along the same lines:

```
1>FAILED: obj/third_party/libyuv/libyuv_internal/cpu_id.obj
1>ninja -t msvc -e environment.winuwp_x64 -- "c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\bin\hostx64\x64\cl.exe" /nologo /showIncludes  @obj/third_party/libyuv/libyuv_internal/cpu_id.obj.rsp /c ../../third_party/libyuv/source/cpu_id.cc /Foobj/third_party/libyuv/libyuv_internal/cpu_id.obj /Fd"obj/third_party/libyuv/libyuv_internal_cc.pdb"
1>../../third_party/libyuv/source/cpu_id.cc(209): error C3861: 'getenv': identifier not found
```

I've uninstalled all version of Windows 10 SDK except version 10.1.16299.15.  I've included all components of this SDK, including Debugging Tools.

I'm running the latest version of Visual Studio, version 15.8.5.

Note that I am able to build the current master branch of webrtc-uwp-sdk OK, but my code base makes use of Media, MediaDevice, and a number of other objects that don't appear to have made the jump from m62 to m66.

Any suggestions on what I might be doing wrong, or how to fix the m62 branch if it is a deeper issue, would be greatly appreciated.

Regards,
Joe

**Comment by ChrisVifzack** [comment] 2018-10-11 08:09
I have exactly the same issue. Help is much appreciated.

**Comment by jamescadd** [comment] 2018-10-11 17:08
I have reproduced this as well.  Adding @SergioOpenPeer for any ideas.

**Comment by cy238** [comment] 2018-11-04 21:50
Same issue here.  The problem might be that buildWebRTC.bat uses the includes for SDK version 17134, even if the project is set to 16299. 17134 seems to be the default SDK for the newer VS versions, meaning you cannot uninstall it without uninstalling VS itself and simply deleting it just breaks everything.
I couldn't figure out how to force the build script to use a specific SDK version yet, but I guess doing so could fix it.

**Comment by jamescadd** [comment] 2018-11-04 22:39
@cy238 is the reason you're using M62 for the Unity support? Also do you need the full source or would a Dll drop suffice? Unity support with the 2018 toolchain started rendering video late last week on M66, would that be an option?

**Comment by cy238** [comment] 2018-11-04 22:48
@jamescadd Yes, we're trying to integrate WebRTC into a Unity HoloLens project. There's a commit in the M62 branch that fixes a crash when using data channel that is not included in the M62 nuget dll. So an updated dll would suffice, I guess.
Does M66 support mixed reality capture yet?

**Comment by DanAndersen** [comment] 2019-01-23 23:15
Update for anyone coming across this issue later: https://github.com/webrtc-uwp/webrtc-uwp-sdk/issues/57 describes this getenv/_putenv issue and offers a workaround: replace your m62 version of a certain header with this one from the m66 branch: https://github.com/webrtc-uwp/webrtc-windows/blob/Robin/m66-msidl/third_party/winuwp_compat/winuwp_compat_std.h

**Comment by jamescadd** [comment] 2019-01-23 23:34
FYI here's the latest M62 Unity source - it references newer Unity tooling and builds with the latest VS & SDK installed: https://github.com/ortclib/ortclib-sdk/tree/Mosa/m62-peercc-unity

**Comment by jamescadd** [comment] 2019-01-24 17:16
@DanAndersen which branch were you still seeing this issue on?  The header in /releases/m62 is the same as m66 so I expected it to be resolved.

**Comment by DanAndersen** [comment] 2019-01-24 17:31
@jamescadd Ah, sorry, this was on an earlier commit (I have a forked version of the code that is from an older commit of the Mosa/20180320-peercc-unity branch). Shouldn't be an issue anymore.

**Comment by jamescadd** [comment] 2019-01-24 18:09
@DanAndersen thanks for closing the loop!  I'll close this issue for now as it should be resolved.

**Comment by jamescadd** [comment] 2019-02-06 14:57
This is now resolved thanks to some additional merges.

**Closed by jamescadd** 2019-02-06 14:57 UTC
