### ISSUE TITLE
M66: Prepare script is broken (argument parsing among other things)

### ISSUE THREAD

**Issue by Holo-Krzysztof** [webrtc-uwp/webrtc-uwp-sdk#68] opened 2018-09-03 13:30 UTC
Running `prepare.bat -target webrtc` as I did before doesn't work anymore; all I get is a `"Diagnostic finished"` message. The script seems to be run in diagnostic mode even though I didn't specify that on the command line.

When I omit the target parameter it fails with the following trace:
```
Traceback (most recent call last):
  File "C:\webrtc-uwp-sdk\webrtc\xplatform\depot_tools\download_from_google_storage.py", line 604, in <module>
    sys.exit(main(sys.argv))
  File "C:\webrtc-uwp-sdk\webrtc\xplatform\depot_tools\download_from_google_storage.py", line 600, in main
    options.extract)
  File "C:\webrtc-uwp-sdk\webrtc\xplatform\depot_tools\download_from_google_storage.py", line 388, in download_from_google_storage
    auto_platform))
  File "C:\webrtc-uwp-sdk\webrtc\xplatform\depot_tools\download_from_google_storage.py", line 164, in enumerate_input
    raise FileNotFoundError('%s not found.' % input_filename)
__main__.FileNotFoundError: buildtools\win\gn.exe.sha1 not found.
Traceback (most recent call last):
  File "C:\webrtc-uwp-sdk\webrtc\xplatform\depot_tools\download_from_google_storage.py", line 604, in <module>
    sys.exit(main(sys.argv))
  File "C:\webrtc-uwp-sdk\webrtc\xplatform\depot_tools\download_from_google_storage.py", line 600, in main
    options.extract)
  File "C:\webrtc-uwp-sdk\webrtc\xplatform\depot_tools\download_from_google_storage.py", line 388, in download_from_google_storage
    auto_platform))
  File "C:\webrtc-uwp-sdk\webrtc\xplatform\depot_tools\download_from_google_storage.py", line 164, in enumerate_input
    raise FileNotFoundError('%s not found.' % input_filename)
__main__.FileNotFoundError: buildtools\win\clang-format.exe.sha1 not found.

CRITICAL ERROR: Failed downloading clang-format.exe

FAILURE:Preparing WebRTC development environment has failed.
```

**Comment by robin-raymond** [comment] 2018-09-03 13:31
I suspect there's a failure literally in the download of clang tools. As for the diagnostics, that needs to be looked into...

**Comment by Holo-Krzysztof** [comment] 2018-09-03 13:43
It seems to be a path/workdir issue. The file in question does exist under `webrtc-uwp-sdk\webrtc\xplatform\buildtools\win`.

**Comment by vmancic** [comment] 2018-09-03 17:45
It works for me.

I have cloned m66 using this command:
git clone --recursive https://github.com/webrtc-uwp/webrtc-uwp-sdk.git -b releases/m66

I have run then prepare, and it was successful. 

C:\Work\sep03-webrtc2-m66\webrtc-uwp-sdk>bin\prepare.bat -target webrtc

Running prepare script ...

Running script parameters:
Target: webrtc
Platform: all
Log level: 2
Preparing webrtc development environment ...
Preparing development environment for ARM, x64, x86 and win32 platforms ...

Running WebRTC prepare script ...
=================================
Preparing WebRTC development environment for arm, x64, x86 and win32 platforms ...
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
In case pop-up window 'Git Credential Manager for Windows' appears after clang download, just click 'Cancel' button.
Updating Clang to 310694-2...
Creating directory C:\Work\sep03-webrtc2-m66\webrtc-uwp-sdk\webrtc\xplatform\webrtc\third_party\llvm-build
Downloading prebuilt clang
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Win/clang-310694-2.tgz .......... Done.
Creating directory C:\Work\sep03-webrtc2-m66\webrtc-uwp-sdk\webrtc\xplatform\webrtc\third_party\llvm-build\Release+Asserts
clang 310694-2 unpacked



Please follow the instructions at https://www.chromium.org/developers/how-tos/build-instructions-windows


Traceback (most recent call last):
  File "tools\clang\scripts\update.py", line 879, in <module>
    sys.exit(main())
  File "tools\clang\scripts\update.py", line 875, in main
    return UpdateClang(args)
  File "tools\clang\scripts\update.py", line 417, in UpdateClang
    CopyDiaDllTo(os.path.join(LLVM_BUILD_DIR, 'bin'))
  File "tools\clang\scripts\update.py", line 367, in CopyDiaDllTo
    dia_path = os.path.join(GetVSVersion().Path(), 'DIA SDK', 'bin', 'amd64')
  File "tools\clang\scripts\update.py", line 354, in GetVSVersion
    vs_toolchain.SetEnvironmentAndGetRuntimeDllDirs()
  File "C:\Work\sep03-webrtc2-m66\webrtc-uwp-sdk\webrtc\xplatform\webrtc\build\vs_toolchain.py", line 44, in SetEnvironmentAndGetRuntimeDllDirs
    Update()
  File "C:\Work\sep03-webrtc2-m66\webrtc-uwp-sdk\webrtc\xplatform\webrtc\build\vs_toolchain.py", line 403, in Update
    subprocess.check_call(get_toolchain_args)
  File "C:\Python27\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'C:\\Work\\sep03-webrtc2-m66\\webrtc-uwp-sdk\\webrtc\\xplatform\\depot_tools\\win_toolchain\\get_toolchain_if_necessary.py', '--output-json', 'C:\\Work\\sep03-webrtc2-m66\\webrtc-uwp-sdk\\webrtc\\xplatform\\webrtc\\build\\win_toolchain.json', '9bc7ccbf9f4bd50d4a3bd185e8ca94ff1618de0b']' returned non-zero exit status 1
0> Downloading buildtools\win\gn.exe...
Success!
Downloading 1 files took 107.590000 second(s)
0> Downloading buildtools\win\clang-format.exe...
Success!
Downloading 1 files took 6.542000 second(s)
Generating WebRTC projects for x64 platform ...
Generating WebRTC projects for x86 platform ...
Generating WebRTC projects for win32 platform ...
Generating WebRTC projects for win32 x64 platform ...

Success: WebRTC development environment is prepared.
=======   WebRTC prepare script summary   =======
=======   platform   =========   result   =======
            arm                 not run
            x64                 prepared
            x86                 prepared
            win32               prepared
=================================================


Success: Development environment is set.
Total execution time: 00:06:39 (399s total)


C:\Work\sep03-webrtc2-m66\webrtc-uwp-sdk>

**Comment by Holo-Krzysztof** [comment] 2018-09-03 17:56
Sorry, I forgot to mention the exact m66 branch I was referring to: it was `Robin/m66-msidl-moved`.

**Comment by vmancic** [comment] 2018-09-03 19:34
You may want to try branch Sergej/20180824-m66-msidl-arm, which is result of merging with Robin/m66-msidl-moved.

I've tried today fresh clone of Sergej/20180824-m66-msidl-arm, and did not have any issue with prepare.

**Comment by Holo-Krzysztof** [comment] 2018-09-04 08:09
Same problem. I suspect something's wrong with my environment.
Maybe because of a VS update? Or because I tried building upstream WebRTC for android once? I don't know.

**Comment by vmancic** [comment] 2018-09-04 09:43
Please check do you have this in your environment:

1) Visual Studio 2017
2) The C++/WinRT Visual Studio extension must be installed - https://marketplace.visualstudio.com/items?itemName=CppWinRTTeam.cppwinrt101804264
3) Windows 10 SDK, version 1803 (10.0.17134.0) - https://developer.microsoft.com/en-us/windows/downloads/sdk-archive More info here: https://blogs.msdn.microsoft.com/chuckw/2018/05/02/windows-10-april-2018-update-sdk/
4) "Debugging Tools for Windows" feature from the Windows 10 SDK must be installed.


This is taken from:
https://github.com/ortclib/ortclib-sdk/blob/Sergej/20180824-m66-msidl-arm/README.md

**Comment by Holo-Krzysztof** [comment] 2018-09-04 10:02
Got all of the above since I use C++/WinRT for daily development.
Could it be because of VS 15.8? I'm sure it worked with 15.7.

**Comment by vmancic** [comment] 2018-09-04 11:35
I am not sure about 15.8, I use 15.7.

**Comment by Holo-Krzysztof** [comment] 2018-09-04 11:48
I updated to 15.8 recently and can't think of anything else that changed (aside from regular Windows updates). Can anyone try it out and confirm that's the issue?

**Comment by vmancic** [comment] 2018-09-05 12:47
I have updated to 15.8 and there is no issue with prepare scripts (branch Sergej/20180824-m66-msidl-arm)

**Comment by robin-raymond** [comment] 2018-09-05 13:57
But if you look at the log, it's clear the issue is that the script is having download issues. @vmancic how do we diagnose what's wrong in this case?

**Comment by Holo-Krzysztof** [comment] 2018-09-06 07:46
I've pulled the newest changes (b3e4176acfa) but I'm still having issues. It still runs in diagnostic mode when I supply args for some reason, but when run without anything I get this:
```
Platform: all
Cpu: all
Log level: 2
Preparing webRTC development environment ...
Preparing development environment for WinUWP and Win32 platforms ...
Preparing development environment for arm, x86, and x64 cpus ...
Preparing development environment for debug and release configurations ...
Pip and pywin32 setup...
The system cannot find the batch label specified - makeDirectory
        1 file(s) copied.
COPY webrtc\xplatform\templates\gn\idl_BUILD.gn webrtc\xplatform\webrtc\third_party\idl\BUILD.gn
The system cannot find the path specified.

CRITICAL ERROR: ORTC invalid folder structure. Unable to copy WebRTC template solution file


FAILURE:Preparing environment has failed

Total execution time: 00:00:00 (0s total)
```

**Comment by Holo-Krzysztof** [comment] 2018-09-06 11:56
Since the script that actually does the work is `prepareWebRtc.bat` I've hardcoded the loglevel to 4 and invoked it. Here's the output:
```
Running WebRTC prepare script ...
=================================
Preparing WebRTC development environment for WinUWP and win32 platforms ...
Preparing WebRTC development environment for arm, x86, x64 cpus ...
          winuwp                 x64               not run
          win32                  x86               not run
          win32                  x64               not run
===================================================================

Executing prepareWebRTC function
Pushed webrtc\xplatform\webrtc path
Executing generateChromiumFolders function
chromium\src folder already exists
chromium\src\tools folder already exists
chromium\src\third_party folder already exists
chromium\src\third_party\winsdk_samples folder already exists
chromium\src\third_party\libjingle\source\talk\media\testdata\ folder already exists
third_party folder already exists
tools folder already exists
Executing makeJunctionLinks function
Path "third_party\protobuf" already exists
Path "chromium\src\third_party\expat" already exists
Path "third_party\expat" already exists
Path "chromium\src\third_party\googletest" already exists
Path "third_party\googletest" already exists
Path "third_party\googletest\src" already exists
Path "third_party\libsrtp" already exists
Path "third_party\llvm-build" already exists
Clang already exists, skipping clang update...
Path "third_party\libyuv" already exists
Path "third_party\openmax_dl" already exists
Path "third_party\libjpeg_turbo" already exists
Path "third_party\winuwp_compat" already exists
Path "third_party\winuwp_h264" already exists
Path "third_party\gflags" already exists
Path "third_party\gflags\src" already exists
Path "third_party\winsdk_samples" already exists
Path "tools\gyp" already exists
Path "tools\clang" already exists
Path "third_party\harfbuzz-ng" already exists
Path "third_party\freetype" already exists
Path "third_party\zlib" already exists
Path "third_party\libpng" already exists
Path "third_party\icu" already exists
third_party\idl folder already exists
Path "third_party\idl\cryptopp" already exists
Path "third_party\idl\zsLib" already exists
Path "third_party\idl\zsLib-eventing" already exists
Path "sdk\windows" already exists
Path "sdk\idl" already exists
Path "build" already exists
Path "chromium\src\third_party\jsoncpp" already exists
Path "chromium\src\third_party\jsoncpp\source" already exists
Path "third_party\boringssl" already exists
In
The system cannot find the path specified.

CRITICAL ERROR: COULD NOT CREATE SYMBOLIC LINK TO third_party\boringssl\src FROM ..\boringssl

FAILURE:Preparing WebRTC development environment has failed.
=======   WebRTC prepare script summary   =======
=======   platform   =========   cpu   =========   result   =======
          winuwp                 arm               not run
The system cannot find the batch label specified - print
          winuwp                 x64               not run
          win32                  x86               not run
          win32                  x64               not run
===================================================================

The system cannot find the path specified.
Path "third_party\boringssl\src" already exists

CRITICAL ERROR: WebRTC invalid folder structure. chromium\src\third_party\usrsctp does not exist

FAILURE:Preparing WebRTC development environment has failed.
=======   WebRTC prepare script summary   =======
=======   platform   =========   cpu   =========   result   =======
          winuwp                 arm               not run
The system cannot find the batch label specified - print
          winuwp                 x64               not run
          win32                  x86               not run
          win32                  x64               not run
===================================================================
```

Can you notice anything suspicious?

**Comment by vmancic** [comment] 2018-09-10 14:42
I have noticed this in your latest log output:

"In
The system cannot find the path specified."

"In" here is just beginning of this print from the code "In path %~1 creating symbolic link for %~2 to %~3"

But since "path" was not under quotes, I think this might causing the problem, though I don't understand why I don't have this issue in that case.

I put potential fix with print under quotes, so please do fresh clone of webrtc-uwp, branch Vladimir/20180907-m66-msidl-arm, and run prepare.bat with argument "-loglevel 4" (without hard-coding in prepareWebRtc.bat), and give me the log.

**Comment by Holo-Krzysztof** [comment] 2018-09-11 08:39
It doesn't pick up the `-loglevel` argument. All I get from `C:\webrtc-uwp-sdk>bin\prepare.bat -loglevel 4` is this:
```
================================================================================

Diagnostic finished
```

Here's the output without args:
```
Platform: all
Cpu: all

CRITICAL ERROR: ORTC invalid folder structure. ortc\xplatform\curl does not exist


FAILURE:Preparing environment has failed

Total execution time: 00:00:00 (0s total)
```

Hardcoding loglevel to 4 doesn't change the output at all.

**Comment by vmancic** [comment] 2018-09-11 10:04
I have questions:

1) I am not sure from your response did you actually try fresh clone - if you did not, please try and run prepare.
2) can you check how is the variable diagnostic in prepare.bat set; If it is set to 1, please set it to 0 (after fresh clone, it is set to 0)

**Comment by Holo-Krzysztof** [comment] 2018-09-11 14:53
That's good to hear.
Why does it happen, though?

**Comment by vmancic** [comment] 2018-09-11 22:11
Please check how git handles line endings. 

https://github.com/ortclib/ortclib-sdk/blob/master/README.md

Try 'git config core.autocrlf', and if it return false, set core.autocrlf to true with 'git config --global core.autocrlf true'

Then do fresh clone again, and run prepare.

**Comment by Holo-Krzysztof** [comment] 2018-09-12 07:14
Yep, it's false. I remember setting it to true when I first cloned the repo but likely forgot to do that on subsequent clones. I'll try again and report back.

**Comment by jamescadd** [comment] 2018-11-13 16:18
@ispysoftware That is true, Python v2 should be used. @Holo-Krzysztof  is this issue still outstanding for you?

**Comment by jamescadd** [comment] 2018-11-13 16:29
Great, I'll close this out.  @SergioOpenPeer has a new build process nearly complete which should be unaffected by line endings (look for this when M71 is ready).

**Closed by jamescadd** 2018-11-13 16:29 UTC

**Comment by ispysoftware** [comment] 2018-11-13 23:55
i have both python v2 and v3 installed - if v3 is higher up in the path variable you will get these errors
