### ISSUE TITLE
Dead ends,How to start

### ISSUE THREAD

**Issue by YUEJINYUAN** [webrtc-uwp/webrtc-uwp-sdk#126] opened 2019-03-18 09:22 UTC
@morosev 
from branch Mosa/m71-unity-fixes
After getting your branch
First step I try to generate
Webrtc/windows/solutions/WebRtc.Universal.sln
In this solution: PeerConnectionClient. WebRtc seems to lack Org. WebRtc. winmd, emmm... I don't know how to get it yet. So I turned to webrtc/windows/solutions/WebRtcUnity.Universal.sln in the second step.
In this solution: there are many. CPP files missing, as well as Org. WebRtc. winmd.
I think it's probably a lack of some pre-preparation, and then look at the steps of environmental preparation.
The bin directory was not found in this branch (although it was written on readme), so I decided to try the master's environmental preparation steps,... Bin / prepare... And I got stuck in a dead end.
Every time it executes, it downloads Python 2.7 repeatedly, even though it has been installed before, then it updates pip, and finally dies in one of the sentences. I'm surprised that it will die on print. Now I don't know what to do. Master and this branch make me confused.

This is my reply to prepare. bat in the main branch.

Running script with default parameters:
Target: all (Ortc and WebRtc)
Platform: all (winuwp, win32)
Cpu: all (x64, x86, arm)
Log level: 2 (warning)

Running prepare script ...

Preparing webRTC development environment ...
Preparing development environment for WinUWP and Win32 platforms ...
Preparing development environment for arm, x86, and x64 cpus ...
Preparing development environment for debug and release configurations ...
Pip and pywin32 setup...
Collecting pip
  Using cached https://files.pythonhosted.org/packages/d8/f3/413bab4ff08e1fc4828dfc59996d721917df8e8583ea85385d51125dceff/pip-19.0.3-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-19.0.3
Requirement already satisfied: pywin32 in c:\programdata\anaconda3\lib\site-packages (223)
已复制         1 个文件。
COPY webrtc\xplatform\templates\gn\idl_BUILD.gn webrtc\xplatform\webrtc\third_party\idl\BUILD.gn

Running WebRTC prepare script ...
=================================
Preparing WebRTC development environment for WinUWP and win32 platforms ...
Preparing WebRTC development environment for arm, x86, x64 cpus ...
Preparing WebRTC development environment for debug and release configurations ...
已复制         1 个文件。
已复制         1 个文件。
已复制         1 个文件。
已复制         1 个文件。
In case pop-up window 'Git Credential Manager for Windows' appears after clang download, just click 'Cancel' button.
  File "tools\clang\scripts\update.py", line 119
    print ' Done.'
                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(' Done.')?

CRITICAL ERROR: WebRTC invalid folder structure. chromium\src\third_party\llvm-build does not exist

FAILURE:Preparing WebRTC development environment has failed.
=======   WebRTC prepare script summary   =======
=======   platform   =========   cpu   =========   result   =======
          winuwp                 arm               not run
          winuwp                 x86               not run
          winuwp                 x64               not run
          win32                  x86               not run
          win32                  x64               not run
===================================================================

系统找不到指定的路径。
In path . creating symbolic link for third_party\llvm-build to chromium\src\third_party\llvm-build
为 third_party\llvm-build <<===>> chromium\src\third_party\llvm-build 创建的联接
Path "third_party\llvm-build" already exists
Clang already exists, skipping clang update...
系统找不到指定的路径。
python: can't open file '<unprintable file name>': [Errno 2] No such file or directory

CRITICAL ERROR: Failed downloading gn.exe

FAILURE:Preparing WebRTC development environment has failed.
=======   WebRTC prepare script summary   =======
=======   platform   =========   cpu   =========   result   =======
          winuwp                 arm               not run
          winuwp                 x86               not run
          winuwp                 x64               not run
          win32                  x86               not run
          win32                  x64               not run
===================================================================

Where should I start and how to meet the preconditions of these solutions? I hope to get your answer.

**Comment by jamescadd** [comment] 2019-03-18 19:38
Hello - newer branches do not require the execution of prepare.bat.  Instead, you can recursively clone the branch, open the .sln file, and begin building in Visual Studio.  Can you let us know if this works?  You may need to create a new clone now that prepare has been run (again, make sure to do --recursive).

**Comment by antonpadova** [comment] 2019-03-19 02:36
Hello - I checkout this branch and run clientunity demo but can not run, because missing a lot library, could you tell me how to fix this?

**Comment by YUEJINYUAN** [comment] 2019-03-19 06:12
Emmm... Now I make sure that the content of my recursive cloning is releases / m71. I don't know if you're talking about this repository. Here's my attempt at this repository.

Following readme, I opened the WebRtc.Universal.sln solution, and I tried to identify releases/x86 to generate any of the projects (I had tried peerconnection Client as a startup item and failed, so I wanted to see if others could meet the criteria), most of which pointed to .cpp file lost,the directory is “ ..\..\..\..\xplatform\webrtc\sdk\windows\wrapper\xxxx.cpp ” , so I went to the xplatform folder to find it, and there was no windows folder under sdk. Emmm... should be broken here. In addition, I found similar directories under xplatform\webrtc-apis. Are these . cpp files correct, or how can I change them? Thank you for your help.

**Comment by morosev** [comment] 2019-03-19 15:44
@YUEJINYUAN @antonpadova If you want to build a Unity version of the library, just follow the steps described in the README: https://github.com/webrtc-uwp/webrtc-uwp-sdk/tree/releases/m71. All the latest changes related to Unity (HoloLens) are merged in to that branch. There is no need to do any additional action beyond those described in the instructions.

**Comment by datHSOsnabrueck** [comment] 2019-03-19 17:02
@morosev  hey, i just clone the branch https://github.com/webrtc-uwp/webrtc-uwp-sdk/tree/Miodrag/m71-unity-fix few hour ago and finished windows build part. Now I am stuck on the part Running Unity Peer Connection Client application on HoloLens device. When i open the project in unity editor and try to build the project in build setting. I get those error. Could you help me ?

I am running Unity 2018.3.7f1 (64-bit).
<img width="1280" alt="Capture1" src="https://user-images.githubusercontent.com/33029648/54626197-fd6bbe00-4a70-11e9-9e4c-a380e06fe014.PNG">

Is there any difference from release/m71 and the branch above ?

waiting for answer ...

**Comment by morosev** [comment] 2019-03-19 19:06
Better use `releases/m71`. It is the most recent.
I've just hit the same issue. It looks like Unity and non Unity build interfere between each other for PeerConnectionCore project. When non Unity build (PeerConnectionClientCore project) is performed before Unity build (PeerConnectionClientUnityCore project) the first project leaves some NuGet libraries in temporary folder and therefore the build for Unity takes a reference to the newer .NET Runtime library (4.2.1.0). Rebuild of PeerConnectionClientUnityCore solved the issue for me.

**Comment by datHSOsnabrueck** [comment] 2019-03-19 20:38
> Better use `releases/m71`. It is the most recent.
> I've just hit the same issue. It looks like Unity and non Unity build interfere between each other for PeerConnectionCore project. When non Unity build (PeerConnectionClientCore project) is performed before Unity build (PeerConnectionClientUnityCore project) the first project leaves some NuGet libraries in temporary folder and therefore the build for Unity takes a reference to the newer .NET Runtime library (4.2.1.0). Rebuild of PeerConnectionClientUnityCore solved the issue for me.
> @datHSOsnabrueck

well, thank for the reply. I believe your aswer will solve the problem, however I just clone the release/m71 branch and do the instruction from README.md and now I can build the VS solution from unity without any problem :) 

Another question would be: Since I have already created a hololens project with unity,  I would like to implement this peercc samples as additional feature in my existing project.  Are there any description how to do that ? a link to the existing issues would be nice ;)

**Comment by YUEJINYUAN** [comment] 2019-03-22 01:29
Thank you for your help. Now it has no problem building sdk. I replaced the environment of Python 2 and manually downloaded the missing files he needed (I am in China, even the agent can hardly get those required procedures, can only download them manually), the best wishes

**Comment by YUEJINYUAN** [comment] 2019-03-22 03:43
There seems to be no problem at the time of generation, but after deployment and debugging, when I click on connect (modify the script to point the server to self-hosting), there is an unhandled exception: read access rights conflict.

The conflict code is:

Const il2cpp_hresult_t HR = identity - > Query Interface (IAsyncOperation_1_t1181249698:: IID, reinterpret_cast < void**> (& return Value));



Conflict file location:

Common windows samples PeerCC ClientUnity Ho-App Il2CppOutput Project Source il2cppOutput Bulk_Windows Runtime Metadata_0



@morosev Which step was I wrong?

**Comment by morosev** [comment] 2019-03-25 18:44
@datHSOsnabrueck There are no instructions about WebRTC UWP library integration into Unity, but you can follow the logic implemented in this file: https://github.com/webrtc-uwp/PeerCC/blob/releases/m71/ClientUnity/Assets/Scripts/ControlScript.cs
The libraries produced by PeerConnectionClientUnityCore build should be copied to the following locations:
```
-- WSA
    |
    -- PeerConnectionClientCore.dll
    |
    -- x86
        |
        -- MediaEngineUWP.dll
        |
        -- Org.WebRtc.dll
        |
        -- WebRtcScheme.dll
```

**Comment by morosev** [comment] 2019-03-25 18:50
@YUEJINYUAN I'm not sure about the problem you have. It's a bit harder to debug IL2CPP generated code. But everything should be just correct if you follow the instructions from README. Can you please provide more lines from the error trace?

**Comment by morosev** [comment] 2019-03-25 18:54
@datHSOsnabrueck H.264 is the best choice currently for HoloLens because the HW acceleration is employed for that codec (VP8 and VP9 are processed on CPU).

**Comment by markgrossnickle** [comment] 2019-03-25 18:55
@datHSOsnabrueck 
Check out @bengreenier's work here:
https://github.com/bengreenier/MixedRealityToolkit-Unity/tree/feature/webrtc-squash

He is in the process of bringing it into MRTK. It is being discussed as an extension to that library and has in it a Unity based project.  I've been able to get it running on a Hololens, though the performance is real slow.

**Comment by morosev** [comment] 2019-03-25 19:03
Another sample: https://github.com/bengreenier/webrtc-unity-plugin

**Comment by markgrossnickle** [comment] 2019-03-25 19:06
That is the same one, only a few days behind the webrtc-squash one.  Though it does allow you to get just the code needed rather than grabbing all of MRTK just for his extension.

**Comment by datHSOsnabrueck** [comment] 2019-03-26 07:56
> @datHSOsnabrueck There are no instructions about WebRTC UWP library integration into Unity, but you can follow the logic implemented in this file: https://github.com/webrtc-uwp/PeerCC/blob/releases/m71/ClientUnity/Assets/Scripts/ControlScript.cs
> The libraries produced by PeerConnectionClientUnityCore build should be copied to the following locations:
> 
> ```
> -- WSA
>     |
>     -- PeerConnectionClientCore.dll
>     |
>     -- x86
>         |
>         -- MediaEngineUWP.dll
>         |
>         -- Org.WebRtc.dll
>         |
>         -- WebRtcScheme.dll
> ```
@morosev 
well after copying the dll to the specific folder. I could implement the peercc scene to my current project. When I start the project and call the peercc scene, I am able to connect to server and I am able to call. But there are 2 problems:
1) available peerlist in hololens is empty ( same behaviour like the standalone peercc project)
2) I can only see the video from pc client. The remote and local video surface dont turn on at all.

I am not sure about the signalling and conductor script so i copy the whole clientcore folder  to mycurrent project folder and set the player settings with internetclient, internetclientserver,privatnetworkclientserver,webcam.

The sample above does not seem to work either. I faced a bunch of incompatibility with my current unity version

**Comment by morosev** [comment] 2019-03-27 19:38
@datHSOsnabrueck I'm glad that you got it running. Have you tried using local PeerCC Server app. It could be built from the solution project `PeerConnectionServer.Utility`.
I have tested the app in MR Simulator and performances are good.

**Comment by datHSOsnabrueck** [comment] 2019-03-27 19:57
@morosev  well I just use the server executable from here [https://github.com/Microsoft/WebRTC-universal-samples/tree/master/Samples/PeerCC-Sample/Server](url)  and the other 2 clients generated from `releases/m71`.
I do not take any change from `controlscript.cs` or others.
I will take a look at your solution with `PeerConnectionServer.Utility` and will give an update later on.

The last thing I would ask is about the video mode.
Currently with the peercc sample both hololens and pc can see local and remote video.
I would like to have expectation like this:
1)  see only hololens camera view in my pc 
2) see only pc camera view in hololens.
 I just try to manipulate the `controlscript.cs` by remove the `localvideosurface` and anything relate to that. However 2) success but 1) doesn´n. Could you lend me your help again?

**Comment by datHSOsnabrueck** [comment] 2019-04-01 06:56
@morosev  Well I cant build the project you mention above
I use this branch
[https://github.com/webrtc-uwp/webrtc-windows/tree/releases/m71/projects/msvc/PeerConnectionServer.Utility](url)
VS. Log

> 1>------ Build started: Project: PeerConnectionServer.Utility, Configuration: Debug Win32 ------
1>python: can't open file 'C:\Users\FLammers\Desktop\Dat\webrtc-windows\projects\msvc\PeerConnectionServer.Utility\..\..\..\..\..\scripts\run.py': [Errno 2] No such file or directory
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073: The command "call python "C:\Users\FLammers\Desktop\Dat\webrtc-windows\projects\msvc\PeerConnectionServer.Utility\..\..\..\..\..\scripts\run.py" -a prepare build -u peercc_server -p win --cpus x86 -c Debug --noColor
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073: :VCEnd" exited with code 2.
1>Done building project "PeerConnectionServer.Utility.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by morosev** [comment] 2019-04-01 14:00
@datHSOsnabrueck OK. We will check the server application build. In the meantime you can download the server instance from the following link: https://1drv.ms/u/s!Aqwra8GVhH71oFRx9ayxHR6wxZzx

Unity application failure is a known issue. We are doing on fix for that. I filed the issue here: #134

Thanks for reporting all the problems.

**Comment by morosev** [comment] 2019-04-22 18:50
@datHSOsnabrueck Crash on every third call attempt was produced by wrong  IL2CPP code conversion for IVector structure. The problem is fixed in the latest version of Unity Editor.

**Closed by morosev** 2019-04-22 18:50 UTC
